const https = require('https');

const TOKEN = '***REDACTED-GH-TOKEN***';
const PR_NUMBER = '1317';
const REPO = 'lukso-network/docs';

const commentBody = `## Fixes Needed

@CJ42 @JordyDutch

### 1. Remove Logo Image (setting-your-grid.md)

**Remove deze regel (regel 9):**
\`\`\`html
<img width="600" alt="LUKSO Agent Grid Example" src="https://universaleverything.io/0x293E96ebbf264ed7715cff2b67850517De70232a?grid=trade-$lukso" align="center" />
\`\`\`

En de lege regel erna.

### 2. Fix Duplicate Menu Item (sidebars.js)

De duplicate "🎨 Setting your Grid" komt doordat het handmatig toegevoegd is EN autogenerated.

**Huidige code:**
\`\`\`javascript
{
  type: 'category',
  label: '🧃 Grid & Mini-Apps',
  items: [
    'learn/mini-apps/setting-your-grid',  // ← Handmatig toegevoegd
    {
      type: 'autogenerated',
      dirName: 'learn/mini-apps',  // ← Dit genereert ALLE files inclusief setting-your-grid
\`\`\`

**Fix:** Verwijder de handmatige regel of gebruik een andere structuur:
\`\`\`javascript
{
  type: 'category',
  label: '🧃 Grid & Mini-Apps',
  items: [
    // Verwijder deze regel: 'learn/mini-apps/setting-your-grid',
    {
      type: 'autogenerated',
      dirName: 'learn/mini-apps',
\`\`\`

Of als je setting-your-grid BOVEN de autogenerated items wilt:
\`\`\`javascript
{
  type: 'category',
  label: '🧃 Grid & Mini-Apps',
  items: [
    'learn/mini-apps/setting-your-grid',
    {
      type: 'autogenerated',
      dirName: 'learn/mini-apps',
      // Exclude setting-your-grid om duplicate te voorkomen
    }
\`\`\`

Ik kan de fixes toepassen als je de PR update met write permissions.`;

const data = JSON.stringify({ body: commentBody });

const options = {
  hostname: 'api.github.com',
  path: `/repos/${REPO}/issues/${PR_NUMBER}/comments`,
  method: 'POST',
  headers: {
    'Authorization': `token ${TOKEN}`,
    'User-Agent': 'LUKSOAgent',
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
    'Content-Length': data.length
  }
};

const req = https.request(options, (res) => {
  let responseData = '';
  res.on('data', chunk => responseData += chunk);
  res.on('end', () => {
    const json = JSON.parse(responseData);
    if (json.id) {
      console.log('✅ Comment posted!');
      console.log('URL:', json.html_url);
    } else {
      console.error('❌ Error:', json.message || responseData);
    }
  });
});

req.on('error', (e) => console.error('Error:', e.message));
req.write(data);
req.end();
