-- PostgreSQL Schema for Agent Social Network
-- Generated by Prisma Migration

-- CreateEnum
CREATE TYPE "ReputationType" AS ENUM ('EARN', 'BURN', 'SLASH');

-- CreateTable
CREATE TABLE "agents" (
    "address" TEXT NOT NULL,
    "username" TEXT,
    "metadata" JSONB DEFAULT '{}',
    "reputation_score" INTEGER NOT NULL DEFAULT 0,
    "total_posts" INTEGER NOT NULL DEFAULT 0,
    "first_seen_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_active_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "agents_pkey" PRIMARY KEY ("address")
);

-- CreateTable
CREATE TABLE "posts" (
    "id" TEXT NOT NULL,
    "author_address" TEXT NOT NULL,
    "content_hash" TEXT NOT NULL,
    "content_preview" TEXT,
    "ipfs_cid" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "karma_at_post" INTEGER NOT NULL DEFAULT 0,
    "signature" TEXT NOT NULL,
    "transaction_hash" TEXT,

    CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "follows" (
    "id" TEXT NOT NULL,
    "follower_address" TEXT NOT NULL,
    "following_address" TEXT NOT NULL,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transaction_hash" TEXT,
    "block_number" INTEGER,

    CONSTRAINT "follows_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reputation_events" (
    "id" TEXT NOT NULL,
    "agent_address" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "type" "ReputationType" NOT NULL,
    "reason" TEXT,
    "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "transaction_hash" TEXT NOT NULL,
    "block_number" INTEGER,
    "token_address" TEXT,

    CONSTRAINT "reputation_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "indexer_state" (
    "id" INTEGER NOT NULL DEFAULT 1,
    "last_block_lsp26" INTEGER NOT NULL DEFAULT 0,
    "last_block_reputation" INTEGER NOT NULL DEFAULT 0,
    "last_updated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "indexer_state_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "agents_username_key" ON "agents"("username");

-- CreateIndex
CREATE INDEX "posts_author_address_idx" ON "posts"("author_address");

-- CreateIndex
CREATE INDEX "posts_timestamp_idx" ON "posts"("timestamp");

-- CreateIndex
CREATE INDEX "follows_follower_address_idx" ON "follows"("follower_address");

-- CreateIndex
CREATE INDEX "follows_following_address_idx" ON "follows"("following_address");

-- CreateIndex
CREATE UNIQUE INDEX "follows_follower_address_following_address_key" ON "follows"("follower_address", "following_address");

-- CreateIndex
CREATE INDEX "reputation_events_agent_address_idx" ON "reputation_events"("agent_address");

-- CreateIndex
CREATE INDEX "reputation_events_timestamp_idx" ON "reputation_events"("timestamp");

-- AddForeignKey
ALTER TABLE "posts" ADD CONSTRAINT "posts_author_address_fkey" FOREIGN KEY ("author_address") REFERENCES "agents"("address") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follows" ADD CONSTRAINT "follows_follower_address_fkey" FOREIGN KEY ("follower_address") REFERENCES "agents"("address") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follows" ADD CONSTRAINT "follows_following_address_fkey" FOREIGN KEY ("following_address") REFERENCES "agents"("address") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reputation_events" ADD CONSTRAINT "reputation_events_agent_address_fkey" FOREIGN KEY ("agent_address") REFERENCES "agents"("address") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Insert default indexer state
INSERT INTO "indexer_state" ("id", "last_block_lsp26", "last_block_reputation") VALUES (1, 0, 0);
